In [ ]:
from typing import Annotated
from typing_extensions import TypedDict
from langgraph.graph import StateGraph, START, END
from langgraph.graph.message import add_messages
from langchain_anthropic import ChatAnthropic
from pydantic import BaseModel, Field
import os
from langchain_core.tools import tool
from langgraph.graph import MessagesState
from langchain_core.messages import SystemMessage, HumanMessage, ToolMessage
from langchain_core.messages import ToolMessage
from typing import Literal
from IPython.display import Image, display
import pandas as pd
import ast


# Set API key manually
os.environ["ANTHROPIC_API_KEY"] = ""

In [19]:
llm = ChatAnthropic(
    model="claude-3-5-sonnet-latest",
    api_key=os.getenv("ANTHROPIC_API_KEY"),  # Use the environment variable
    temperature=0.2,
    max_tokens=1024
)

In [20]:
from typing import Union

class Term(BaseModel):
    ASPECT_TERM: Union[list, str] = Field(None, description="list of aspect terms of the given sentence")

structured_llm = llm.with_structured_output(Term)

In [21]:
ate_prompt = """You are Linguistic expert. I want you to find the ASPECT TERM of the review sentence.:
-Examples: 
1. After all that, they complained to me about the small tip.
[noaspectterm] 
2.Chow fun was dry; pork shu mai was more than usually greasy and had to share a table with loud and rude family. 
['Chow fun', 'pork shu mai']
3. We took advanatage of the half price sushi deal on saturday so it was well worth it.
['half price sushi deal']
Now find the ASPECT TERM of the following sentence:
"""

In [22]:
ate_16_test = pd.read_csv("/home/s6moakba/InstructABSA/Dataset/SemEval16/Test/Restaurants_Test.csv")

In [26]:
claude_pred = []
for i, row in ate_16_test.iterrows():
    text = row['raw_text']
    print(i)
    print(text)
    pred = structured_llm.invoke(ate_prompt + text)

    if isinstance(pred.ASPECT_TERM, str):
        try:
            pred.ASPECT_TERM = ast.literal_eval(pred.ASPECT_TERM)  # Convert string to list
        except Exception as e:
            print(f"Error parsing ASPECT_TERM: {e}")
            pred.ASPECT_TERM = []
            
    claude_pred.append(pred.ASPECT_TERM)
    print(pred.ASPECT_TERM)
    print('='*50 )

0
Yum!
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f49496a1250>
[]
==================================================
1
Serves really good sushi.
['sushi']
==================================================
2
Not the biggest portions but adequate.
['portions']
==================================================
3
Green Tea creme brulee is a must!
Error parsing ASPECT_TERM: invalid syntax (<unknown>, line 1)
[]
==================================================
4
Don't leave the restaurant without it.
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f494923e7d0>
[]
==================================================
5
No Comparison
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f494923e7d0>
[]
==================================================
6
– I can't say enough about this place.
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f4948162010>
[]
==================================================
7
It has great sushi and even better service.
['sushi', 'service']
==================================================
8
The entire staff was extremely accomodating and tended to my every need.
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f494908a390>
[]
==================================================
9
I've been to this restaurant over a dozen times with no complaints to date.
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f494908a390>
[]
==================================================
10
Snotty Attitude
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f49492888d0>
[]
==================================================
11
– We were treated very rudely here one time for breakfast.
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f4949099050>
[]
==================================================
12
The owner is belligerent to guests that have a complaint.
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f49496a15d0>
[]
==================================================
13
Good food!
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f49496a15d0>
[]
==================================================
14
– We love breakfast food.
Error parsing ASPECT_TERM: invalid syntax (<unknown>, line 1)
[]
==================================================
15
This is a great place to get a delicious meal.
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f4b75bebd50>
[]
==================================================
16
We never had to wait more than 5 minutes.
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f4943e27dd0>
[]
==================================================
17
The staff is pretty friendly.
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f494917db50>
[]
==================================================
18
The onion rings are great!
Error parsing ASPECT_TERM: invalid syntax (<unknown>, line 1)
[]
==================================================
19
They are not greasy or anything.
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f4948c06310>
[]
==================================================
20
Overrated
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f4948c06310>
[]
==================================================
21
– I was highly disappointed in the food at Pagoda.
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f4949099050>
[]
==================================================
22
The lemon chicken tasted like sticky sweet donuts and the honey walnut prawns, the few they actually give you.....were not good.
['lemon chicken', 'honey walnut prawns']
==================================================
23
The prices are outrageous, especially since the food was actually less satisfying than most neighborhood Chinese establishments.
['prices', 'food']
==================================================
24
Nice ambience, but highly overrated place.
['ambience', 'place']
==================================================
25
I will not go back.
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f494917db50>
[]
==================================================
26
Worst Service I Ever Had
['Service']
==================================================
27
– A group of 5 of us went there for Sunday brunch and sat outside.
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f4b75bebd50>
[]
==================================================
28
Everyone that sat in the back outside agreed that it was the worst service we had ever received.
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f4951451690>
[]
==================================================
29
Our waiter was non-existent and after our food finally arrived over an hour after we ordered, we were not given any water or utensils.
['waiter']
==================================================
30
I complained to the manager, but he was not even apologetic.
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f49501ae450>
[]
==================================================
31
I will never return again.
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f494b49a4d0>
[]
==================================================
32
Fabulous Italian Food!
['Italian Food']
==================================================
33
– I highly recommend Mioposto.
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f49491f91d0>
[]
==================================================
34
I am so happy to have a wonderful Italian restaurant in my neighborhood.
['Italian restaurant']
==================================================
35
The wine list is wonderful and the food reminds me of my recent trip to Italy.
['wine list', 'food']
==================================================
36
I love this restaurant
['restaurant']
==================================================
37
– I will never forget the amazing meal, service, and ambiance I experience at this restaurant.
['meal', 'service', 'ambiance']
==================================================
38
It was absolutely amazing.
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f4943ea01d0>
[]
==================================================
39
The wine list is incredible and extensive and diverse, the food is all incredible and the staff was all very nice, good at their jobs and cultured.
['wine list', 'food', 'staff']
==================================================
40
I have not a bad thing to say about this place.
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f4943f93c90>
[]
==================================================
41
AMAZING.
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f49482c9fd0>
[]
==================================================
42
I cannot wait to go back again this coming weekend!
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f49482c9fd0>
[]
==================================================
43
Mmm... good!
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f494a3aef10>
[]
==================================================
44
– Went there last night with a friend.
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f494a3aef10>
[]
==================================================
45
She had heard from a co-worker about this place.
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f494a387550>
[]
==================================================
46
The food was great!
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f4948c19610>
[]
==================================================
47
It's *very* reasonably priced, esp for the quality of the food.
['food']
==================================================
48
I had the Kafta plate and it was perfect.
['Kafta plate']
==================================================
49
We're going back. :D
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f494a3d9710>
[]
==================================================
50
Finally a meal that you will remember for a long time!
['meal']
==================================================
51
– In a age of incremental cost cutting in restaurants, its nice to see a place that bucks that trend, and just plain delivers high quality food and good service, period.
['food', 'service']
==================================================
52
This is the place to relax and enjoy the finest quality food the industry can offer.
['food']
==================================================
53
Caution - its real food for people who love the best.
['food']
==================================================
54
Some of the food is clearly oriented toward foodies (like me) so if your not a foodie (nothing wrong with that)- head over to McDonalds or some Ruby Tuesday and have at it!
['food']
==================================================
55
If your looking for real quality  (not the BS that is seen on yelp ratings - which allegedly recently got in trouble for "adjusting" ratings), you need to get in here!
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f4948f5c190>
[]
==================================================
56
Very Disappointing
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f494b371950>
[]
==================================================
57
– I took my parents here for their anniversary-very very disappointed!!!
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f4949084250>
[]
==================================================
58
I liked the atmosphere very much but the food was not worth the price.
['atmosphere', 'food', 'price']
==================================================
59
I may not be a sushi guru but I can tell you that the food here is just okay and that there is not much else to it.
['food']
==================================================
60
Rice is too dry, tuna wasn't so fresh either.
['Rice', 'tuna']
==================================================
61
Nothing really came across as outstanding.
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f494a3d9710>
[]
==================================================
62
Very disappointed.
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f4b75bebd50>
[]
==================================================
63
I have eaten here three times and have found the quality and variety of the fish to be excellent.
['quality', 'variety', 'fish']
==================================================
64
However, the value and service are both severely lacking.
['value', 'service']
==================================================
65
Portions contain less fish than one would expect, particularly since prices are in line with the best sushi places in NYC (Masa excluded, of course).
['Portions', 'fish']
==================================================
66
Furthermore, while the fish is unquestionably fresh, rolls tend to be inexplicably bland.
['fish', 'rolls']
==================================================
67
The service ranges from mediocre to offensive.
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f4948161710>
[]
==================================================
68
On a recent trip, our waiter was extremely dismissive, while no less than three staff members waited hand-and-foot on a pair of Japanese girls seated nearby.
['waiter']
==================================================
69
We were then charged for their most expensive sake ($20+ per serving) when we in fact drank a sake of less than half that price.
['sake']
==================================================
70
But Im sure this was just an honest mistake...
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f4948f53090>
[]
==================================================
71
Freshest sushi  – I love this restaurant.
['sushi']
==================================================
72
They pay such detail to everything from miso soup to complex rolls.
['miso soup', 'complex rolls']
==================================================
73
The sashimi was the freshest and most tender I have ever tasted.
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f4b75bebd50>
[]
==================================================
74
Their apps are all delicious.
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f4949293850>
[]
==================================================
75
The only drawback is that this place is really expensive and the portions are on the small side.
['portions']
==================================================
76
But the space is small and lovely, and the service is helpful.
['space', 'service']
==================================================
77
You are bound to have a very charming time.
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f4943e2d2d0>
[]
==================================================
78
Not recommanded!!!
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f494b5d3790>
[]
==================================================
79
– The food was not great & the waiters were rude.
['food', 'waiters']
==================================================
80
It is not worth going at all and spend your money there!!!
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f4948c19610>
[]
==================================================
81
great service
['service']
==================================================
82
– Pretty cheap for sit down Mexican AND downtown.
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f494923f110>
[]
==================================================
83
my service was stellar!
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f494a3d9710>
[]
==================================================
84
the bus boy even spotted that my table was shaking a stabilized it for me.
['table']
==================================================
85
food was fine, with a some little-tastier-than-normal salsa.
['food', 'salsa']
==================================================
86
If you're in the area you shouldn't be disappointed.
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f4943fb21d0>
[]
==================================================
87
Ok.... – Maybe I went in on someone's bad day....
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f4943e2d2d0>
[]
==================================================
88
the food was great, the margaritas too but the waitress was too busy being nice to her other larger party than to take better care of my friend and me.
['food', 'margaritas', 'waitress']
==================================================
89
Took forever to get our order taken, water refills were too much to ask for and the only time she was fast was when we asked for our bill when we could get her attention.
['water refills', 'bill']
==================================================
90
I don't know if I'll be back....
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f4b75bebd50>
[]
==================================================
91
Mama Mia – I live in the neighborhood and feel lucky to live by such a great pizza place.
['pizza place']
==================================================
92
the only problem is you really have to warm up the pizza before it's edible, even when you order ahead.
['pizza']
==================================================
93
BUt once done, it's not too much dough, not too much cheese, not too much sauce.
['dough', 'cheese', 'sauce']
==================================================
94
Best Sushi in town.
['Sushi']
==================================================
95
Have gone to all the top places.
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f494b5d3790>
[]
==================================================
96
Everything you want and more, very fresh.
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f4b75bebd50>
[]
==================================================
97
Its worth the wait, especially since they'll give you a call when the table is ready.
['table']
==================================================
98
The best calamari in Seattle!
['calamari']
==================================================
99
– ...and the best summertime deck experience--they will even bring you a blanket if you get cold in the Seattle evening weather.
['summertime deck', 'blanket']
==================================================
100
A perfect place to take out of town guests any time of the year.
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f494b296750>
[]
==================================================
101
Endless fun, awesome music, great staff!!!
['music', 'staff']
==================================================
102
– By far the best bar in the east village...
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f4943fc2850>
[]
==================================================
103
I went there with some friends one night to play bingo and watch the sox game and it was a blast!
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f4943fc2850>
[]
==================================================
104
Every time "0-sixtynine" is called the bartender buys everyone drinks!
['bartender']
==================================================
105
Been there lots since and its always a good time.
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f49490f0e90>
[]
==================================================
106
Great draft and bottle selection and the pizza rocks.
['draft and bottle selection', 'pizza']
==================================================
107
Definitely has one of the best jukebox's i've seen in a long long time.
['jukebox']
==================================================
108
I FOUND A NEW HOME ON SECOND AVENUE!!!!!!!!!!!!
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f49490aa790>
[]
==================================================
109
– Where can I begin.
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f4943e8f950>
[]
==================================================
110
I can't!!!
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f4b75f18c10>
[]
==================================================
111
Just go there and see for yourself.
Error parsing ASPECT_TERM: malformed node or string on line 1: <ast.Name object at 0x7f4943fb21d0>
[]
==================================================
112
The food is great, the bartenders go that extra mile.
['food', 'bartenders']
==================================================
113

In [29]:
ate_16_test['claude_pred'] = claude_pred

In [30]:
ate_16_test

,raw_text,aspectTerms,claude_pred
0,Yum!,"[{'term': 'noaspectterm', 'polarity': 'none'}]",[]
1,Serves really good sushi.,"[{'term': 'sushi', 'polarity': 'positive'}]",[sushi]
2,Not the biggest portions but adequate.,"[{'term': 'portions', 'polarity': 'neutral'}]",[portions]
3,Green Tea creme brulee is a must!,"[{'term': 'Green Tea creme brulee', 'polarity'...",[]
4,Don't leave the restaurant without it.,"[{'term': 'noaspectterm', 'polarity': 'none'}]",[]
...,...,...,...
671,Two rascally kids were seated near us for the ...,"[{'term': 'noaspectterm', 'polarity': 'none'}]",[]
672,Given that Ray's is a seafood restaurant...wel...,"[{'term': 'noaspectterm', 'polarity': 'none'}]",[]
673,"All considered, I have to say that Ray's Boath...","[{'term': ""Ray's Boathouse"", 'polarity': 'posi...",[Ray's Boathouse]
674,While I could have done without the youth who ...,"[{'term': 'server', 'polarity': 'positive'}, {...","[server, food]"
675,"Oh yeah...the view was good, too.","[{'term': 'view', 'polarity': 'positive'}]",[view]

In [ ]:
ate_16_test['aspectTerms'] = ate_16_test['aspectTerms'].apply(eval)

In [32]:
def extract_terms(aspect_terms_list):
    terms = []
    for aspect in aspect_terms_list:
        terms.append(aspect['term'])
    return terms

ate_16_test['label'] = ate_16_test['aspectTerms'].apply(extract_terms)

In [34]:
ate_16_test['claude_pred'] = ate_16_test['claude_pred'].apply(lambda x: ['noaspectterm'] if x == [] else x)
ate_16_test

,raw_text,aspectTerms,claude_pred,label
0,Yum!,"[{'term': 'noaspectterm', 'polarity': 'none'}]",[noaspectterm],[noaspectterm]
1,Serves really good sushi.,"[{'term': 'sushi', 'polarity': 'positive'}]",[sushi],[sushi]
2,Not the biggest portions but adequate.,"[{'term': 'portions', 'polarity': 'neutral'}]",[portions],[portions]
3,Green Tea creme brulee is a must!,"[{'term': 'Green Tea creme brulee', 'polarity'...",[noaspectterm],[Green Tea creme brulee]
4,Don't leave the restaurant without it.,"[{'term': 'noaspectterm', 'polarity': 'none'}]",[noaspectterm],[noaspectterm]
...,...,...,...,...
671,Two rascally kids were seated near us for the ...,"[{'term': 'noaspectterm', 'polarity': 'none'}]",[noaspectterm],[noaspectterm]
672,Given that Ray's is a seafood restaurant...wel...,"[{'term': 'noaspectterm', 'polarity': 'none'}]",[noaspectterm],[noaspectterm]
673,"All considered, I have to say that Ray's Boath...","[{'term': 'Ray's Boathouse', 'polarity': 'posi...",[Ray's Boathouse],[Ray's Boathouse]
674,While I could have done without the youth who ...,"[{'term': 'server', 'polarity': 'positive'}, {...","[server, food]","[server, food]"
675,"Oh yeah...the view was good, too.","[{'term': 'view', 'polarity': 'positive'}]",[view],[view]

In [44]:
def get_metrics( y_true, y_pred):
        total_pred = 0
        total_gt = 0
        tp = 0
        for gt, pred in zip(y_true, y_pred):
            gt_list = gt.split(', ')
            pred_list = pred.split(', ')
            total_pred+=len(pred_list)
            total_gt+=len(gt_list)
            for gt_val in gt_list:
                for pred_val in pred_list:
                    if pred_val in gt_val or gt_val in pred_val:
                        tp+=1
                        break
        p = tp/total_pred
        r = tp/total_gt
        return p, r, 2*p*r/(p+r)

In [45]:
precision, recall, f1 = get_metrics(ate_16_test['label'].apply(lambda x: ', '.join(x)), ate_16_test['claude_pred'].apply(lambda x: ', '.join(x)))

In [46]:
print(f"Precision: {precision}")   
print(f"Recall: {recall}")
print(f"F1: {f1}")

Precision: 0.6953210010881393
Recall: 0.7319587628865979
F1: 0.7131696428571429

In [43]:
ate_16_test.to_csv("/home/s6moakba/Thesis/agent_practice/claude_performance_16_res.csv")